### ISSUE TITLE
Cumulative report

### ISSUE THREAD

**Issue by kstrohmayer** [semify-eda/tristan#3]
Update the esisting report for M06 - M12

**Comment by adam-hrvth** [comment]
@kstrohmayer I have prepared the following summary for the cumulative report:

semify focused on the RTL implementation of custom instruction set extensions for digital waveform compression and decompression. This work included the development of testbenches for simulation and verification, as well as the creation of FPGA implementations for hardware debugging. Additional sub-modules necessary for RTL implementation have been developed.

If you have any feedback or changes, let me know. Otherwise, I will add it to the SharePoint
